#!/bin/bash
#
# Quick test script for Tesla Owner API tokens generated by Auth for Tesla.
#
# Usage:
#   ./test-token.sh <access_token>
#
# The token can be copied from the app's token detail view.
# This script calls the /api/1/users/me endpoint which requires
# only a valid access token (no vehicle needed).

set -euo pipefail

if [ $# -lt 1 ]; then
    echo "Usage: $0 <access_token>"
    echo ""
    echo "Paste the access token from the app."
    exit 1
fi

TOKEN="$1"

echo "=== Token Info (JWT decode) ==="
# Decode the JWT payload (middle segment) without external tools
PAYLOAD=$(echo -n "$TOKEN" | cut -d. -f2 | tr '_-' '/+' | awk '{
    mod = length($0) % 4
    if (mod == 2) printf "%s==", $0
    else if (mod == 3) printf "%s=", $0
    else printf "%s", $0
}' | base64 -D 2>/dev/null) || true

if [ -n "$PAYLOAD" ]; then
    echo "$PAYLOAD" | python3 -m json.tool 2>/dev/null || echo "$PAYLOAD"
    echo ""

    # Extract expiry
    EXP=$(echo "$PAYLOAD" | python3 -c "import sys,json; print(json.load(sys.stdin).get('exp','?'))" 2>/dev/null) || true
    if [ -n "$EXP" ] && [ "$EXP" != "?" ]; then
        EXP_DATE=$(date -r "$EXP" 2>/dev/null || echo "unknown")
        NOW=$(date +%s)
        REMAINING=$(( EXP - NOW ))
        if [ "$REMAINING" -gt 0 ]; then
            HOURS=$(( REMAINING / 3600 ))
            MINS=$(( (REMAINING % 3600) / 60 ))
            echo "Expires: $EXP_DATE ($HOURS h $MINS min remaining)"
        else
            echo "EXPIRED at $EXP_DATE ($(( -REMAINING )) seconds ago)"
        fi
    fi
else
    echo "(Could not decode JWT payload)"
fi

echo ""
echo "=== Testing /api/1/users/me ==="
RESPONSE=$(curl -s -w "\n%{http_code}" \
    -H "Authorization: Bearer $TOKEN" \
    -H "User-Agent: TeslaApp/4.12.0/AuthAppForTesla" \
    "https://owner-api.teslamotors.com/api/1/users/me")

HTTP_CODE=$(echo "$RESPONSE" | tail -1)
BODY=$(echo "$RESPONSE" | sed '$d')

echo "HTTP $HTTP_CODE"
if [ "$HTTP_CODE" = "200" ]; then
    echo "$BODY" | python3 -m json.tool 2>/dev/null || echo "$BODY"
    echo ""
    echo "Token is VALID."
else
    echo "$BODY"
    echo ""
    echo "Token test FAILED (HTTP $HTTP_CODE)."
fi

echo ""
echo "=== Testing /api/1/products ==="
RESPONSE=$(curl -s -w "\n%{http_code}" \
    -H "Authorization: Bearer $TOKEN" \
    -H "User-Agent: TeslaApp/4.12.0/AuthAppForTesla" \
    "https://owner-api.teslamotors.com/api/1/products")

HTTP_CODE=$(echo "$RESPONSE" | tail -1)
BODY=$(echo "$RESPONSE" | sed '$d')

echo "HTTP $HTTP_CODE"
if [ "$HTTP_CODE" = "200" ]; then
    # Count vehicles / energy products
    COUNT=$(echo "$BODY" | python3 -c "
import sys, json
data = json.load(sys.stdin)
products = data.get('response', [])
vehicles = [p for p in products if 'vin' in p]
energy = [p for p in products if 'energy_site_id' in p]
print(f'{len(vehicles)} vehicle(s), {len(energy)} energy product(s)')
for v in vehicles:
    name = v.get('display_name', 'Unknown')
    vin = v.get('vin', '?')
    state = v.get('state', '?')
    print(f'  - {name} ({vin}) [{state}]')
for e in energy:
    site = e.get('site_name', 'Unknown')
    sid = e.get('energy_site_id', '?')
    print(f'  - {site} (site {sid})')
" 2>/dev/null) || COUNT="(could not parse)"
    echo "$COUNT"
else
    echo "$BODY"
fi

echo ""
echo "Done."
